export const LangStrings = {
  jp: {
    slogan1: "献立、簡単レシピに動画も！",
    slogan2: "必ず見つかるレシピサイト",
    今日のオススメ: "今日のオススメ",
    定番のキーワード: "定番のキーワード",
    最高のシェフ: "最高のシェフ",
    レシピをよむ: "レシピをよむ",
    search: "料理名・食材でレシピをさがす",
    レシピを作る: "レシピを作る",
    もっと: "もっと",
    検索の結果: "検索の結果",
    レシピをよむ一覧: "レシピをよむ一覧",
    材料: "材料",
    作り方: "作り方",
    tips: "料理のコツ・ポイント",
    評価: "評価",
    送信: "送信",
    コメント: "コメント"
  },
  vi: {
    slogan1: "Thực đơn, video công thức nấu ăn đơn giản!",
    slogan2: "Website nơi mà bạn có thể tìm thấy bất kỳ công thức nấu ăn nào",
    今日のオススメ: "Nổi bật trong ngày",
    定番のキーワード: "Từ khóa thông dụng",
    最高のシェフ: "Đầu biếp nổi tiếng",
    レシピをよむ: "Công thức",
    search: "Tìm công thức theo tên món ăn, nguyên liệu",
    レシピを作る: "Tạo công thức",
    もっと: "Thêm",
    検索の結果: "Kết quả tìm kiếm",
    レシピをよむ一覧: "Danh sách công thức",
    材料: "Nguyên liệu",
    作り方: "Cách nấu",
    tips: "Mẹo nấu ăn",
    評価: "Đánh giá",
    送信: "Gửi",
    コメント: "Bình luận",
  },
}
